version: '3.3'

services:
  db:
    image: mysql:8.0.23
# restart: always
    environment:
      MYSQL_DATABASE: 'credits'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our website will be persisted
    volumes:
      - credits-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
# Names our volume
volumes:
  credits-db:
